### ISSUE TITLE
feature: background waylock via commandline flag

### ISSUE THREAD

**Issue by dvzrv** [ifreund/waylock#25]
Hi! I have just moved waylock to the community repository in Arch. :)

I would like to use it in a setup with swayidle, similar to how it can be done for swaylock:

```
exec [ -x /usr/bin/swayidle ] && [ -x /usr/bin/swaylock ] && swayidle -w \
  timeout 300 'swaylock -F -f -e -c 000000' \
  timeout 600 'swaymsg "output * dpms off"' \
  resume 'swaymsg "output * dpms on"' \
  before-sleep 'swaylock -f -c 000000'
```

When replacing the calls to swaylock with waylock, the timeout for switching the screen(s) off via DPMS is never reached (only the colored lock screen is shown):

```
exec [ -x /usr/bin/swayidle ] && [ -x /usr/bin/waylock ] && swayidle -w \
  timeout 300 'waylock' \
  timeout 600 'swaymsg "output * dpms off"' \
  resume 'swaymsg "output * dpms on"' \
  before-sleep 'waylock'
```

I believe it might be because the application never goes to background. Would it be possible to introduce a flag, so that the process is backgrounded/ detached from the calling shell?

Weird, but maybe unrelated to the above:
When using waylock explicitely within a sway session, that has the above setup with swayidle, the screen can be locked and it seemingly also reaches the timeout to switch off the screens, but upon trying to unlock I was met with a lock screen that has many wrong passwords attempts (requiring me to wait 10min and kill the waylock process from a separate TTY).

**Comment by ifreund** [comment]
> Hi! I have just moved waylock to the community repository in Arch. :)

Cool :)

> I believe it might be because the application never goes to background. Would it be possible to introduce a flag, so that the process is backgrounded/ detached from the calling shell?

Is the proposed behavior any different from a simple `setsid -f waylock`?

> When using waylock explicitely within a sway session, that has the above setup with swayidle, the screen can be locked and it seemingly also reaches the timeout to switch off the screens, but upon trying to unlock I was met with a lock screen that has many wrong passwords attempts (requiring me to wait 10min and kill the waylock process from a separate TTY).

Haven't seen anything like this before, if you find a way to reproduce it please open a separate issue.

**Comment by dvzrv** [comment]
> Is the proposed behavior any different from a simple setsid -f waylock?

Probably not! Good point. I was not aware of this being a possibility. I just tried it in my config and it seems to work as expected.
In case you choose to not add this as a convenience functionality, it would probably be a good idea to add it as an example though :)

> Haven't seen anything like this before, if you find a way to reproduce it please open a separate issue.

Will do. I'll test a little more later today, but it might be, that the issue is already solved by the process being backgrounded by swayidle.

**Comment by ifreund** [comment]
Yeah I don't see any reason to implement and maintain code in waylock for this feature when `setsid(1)` work perfectly well. Added a line in the readme mentioning it.

**Comment by ifreund** [comment]
@omeid Thanks for the reminder, I just added a mention of setsid to the readme and man page.

Still don't think a flag for this belongs in waylock.

**Comment by ifreund** [comment]
If anything, this seems like an issue with swayidle's `-w` flag. If it were more granular and could be specified for just some but not all commands there would be no need for this workaround.
